server.port=8080

spring.datasource.url=jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:sti_db}?createDatabaseIfNotExist=true&serverTimezone=Europe/Madrid
spring.datasource.username=${DB_USER:sti_user}
spring.datasource.password=${DB_PASS:sti_pass}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

logging.level.root=INFO
logging.level.org.sti.api=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.config=classpath:logback-spring.xml
